### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by marcinkk** [FallenChromium/Acer-Swift3-2018-hackintosh#1]
Hey, how do you set the keys to adjust the screen brightness on a laptop keyboard ??  Right now it's fn + f12 and fn + key pause.  My bootloader is opencore. In my laptop acer v3-371, the shortcut from adjusting the screen brightness on the keyboard is the shortcut fn + left arrow key and fn + arrow right key.

**Comment by FallenChromium** [comment]
Actually I didn't implement them in my setup at all, I just used F11 and F12 (without FN) as a replacement in my keyboard shortcut settings. Maybe I will look into it a bit later though.
