### ISSUE TITLE
Open Core failed in Niresh build

### ISSUE THREAD

**Issue by ashwinkey04** [FallenChromium/Acer-Swift3-2018-hackintosh#2]
Hey, I am using Niresh's Mojave build. I mounted the EFI partition and replaced all of its content with the one in the release of this repo. Now it doesn't boot up. Could you help me out please

Laptop: Acer Swift 3 SF314 55G
Everything is working fine in Niresh's distro, except the graphic card. My machine uses an Intel UHD 620 (Though MX 250 is also there, it is not supported)

PS: I am an ultra noob in hackintosh-ing

**Comment by FallenChromium** [comment]
I recommend you using a vanilla build because it's the only way to have hackintosh updates working properly. Also this repository is compatible only with macOS 10.15+, so you may have better luck with Catalina.

**Comment by ashwinkey04** [comment]
Thanks for the reply mate @FallenChromium. I eventually went with vanilla oc guide and sort of got it done. I am still not able to get the internal mic working. Any comments on that would be really nice. [This](https://www.github.com/ashwinkey04/oc-efi) is my efi configuration

**Comment by FallenChromium** [comment]
For the microphone you can check advice from the last post of #3 , you may have luck in fixing this too.
