### ISSUE TITLE
trackpad not here

### ISSUE THREAD

**Issue by federicotrevisani12** [FallenChromium/Acer-Swift3-2018-hackintosh#3]
Hey, nice job! I have a problem. As the title reports, I'm still unable to use trackpad. I left all the config.plist and ACPI folder untouched (do I need to remove the .dsl files btw?), I did what you suggested, but absolutely nothing to do apparently. Let me know!

**Comment by FallenChromium** [comment]
Hello! Thanks for your feedback :). Please send a ioregistryexplorer dump and en exact model of your laptop so I could understand which exact chip your laptop uses. There may be some troubles with kext injection though, which OpenCore addressed with 0.6.0 release, and I will update this repo quite soon. For now, please send some debug files and additional info so I could help you! Removing DSL is not necessary, but you can do it if you want.

**Comment by federicotrevisani12** [comment]
Hey, thanks for the answer, to fix it I just patched my dumped DSDT with Windows 10 patch and GPIO controller. Now it’s ok! The only thing it’s not working is microphone. I noticed that Netflix and Apple TV can’t stream, but they’re secondary problem.

**Comment by FallenChromium** [comment]
For Apple TV and Netflix you may find [this](https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#testing-hardware-acceleration-and-decoding) guide useful. As of the trackpad, it was a wise choice :). You see, from model to model trackpad implementation and controller model are different, so my instructions and patches can't cover them all, I am glad you solved it yourself. As I understood you have a different model from the one that I use (mine is SF315-51G). So, yours has different audio chip from Realtek. Try different common layouts IDs like 1 or 3, it might help. More about that [here](https://dortania.github.io/OpenCore-Post-Install/universal/audio.html#finding-your-layout-id ), that's the place where you should modify the config: https://github.com/FallenChromium/Acer-Swift3-2018-hackintosh/blob/57951a8801b13bd38bbc19c29402e21f1a338058/OC/config.plist#L388
