### ISSUE TITLE
an internet connection is required to install mac os

### ISSUE THREAD

**Issue by mhmdiqbal** [FallenChromium/Acer-Swift3-2018-hackintosh#4]
issue when select reinstall mac os

**Comment by FallenChromium** [comment]
That's because you reinstall it from the recovery partition, make sure you make a flash drive with a full installer (it is sized around 12GB for Big Sur and around 7 gigs for Catalina)

**Comment by mhmdiqbal** [comment]
> That's because you reinstall it from the recovery partition, make sure you make a flash drive with a full installer (it is sized around 12GB for Big Sur and around 7 gigs for Catalina)

Ok thanks, let me try it

**Comment by sbruccu** [comment]
i have the same issue u resolve?
