### ISSUE TITLE
OpenCore has been updated and now supports Intel WiFi cards, hope you'll add it soon.

### ISSUE THREAD

**Issue by adimrsingh** [FallenChromium/Acer-Swift3-2018-hackintosh#5]

**Comment by FallenChromium** [comment]
I don't have an Intel wifi card with me but I may investigate it if you want. As far as I know there are speed problems though and it won't work as well as Broadcom does, so I recommend using Broadcom Wi-Fi card instead

**Comment by FallenChromium** [comment]
UPD: I don't own a laptop anymore, so I won't enable Intel Wi-Fi card myself, I have no way to test if it works. If a tested Pull Request will be submitted though I'll happily integrate the changes into my repo though!
