### ISSUE TITLE
acer-swift-3-sf315-52-52yn

### ISSUE THREAD

**Issue by professortex** [FallenChromium/Acer-Swift3-2018-hackintosh#6]
Good day, I found your GitHub post googling my kids Acer swift 3 laptops. I was using clover to run Mojave for their  remote schooling, however I’m new to this and the units were not finished properly. With clover I was able to get most of the hardware working. 

The things that work are as follows: display with brightness control. USB ports, not sure if they are running at the best speeds though. Keyboard with backlight. Webcam though grainy. I replaced the ngff WiFi card, so bt and WiFi works natively. Removed the 16gb optane memory and swapped in a wd 500gb ssd.

Problem areas, again because I’m a noob: no audio output or mic, kids are complaining having to use bt and usb headphones. No track-pad, again I’m a bad dad. No sd card. No fingerprint reader.

I recently wiped my son’s unit and redid it using your acer swift3 2018 download. Now its on Catalina with the same exact issues as before. No audio, track-pad, etc. when the unit boots there’s a string of text scrolling by so fast I can’t read then I get a menu to boot from the ssd. Basically I’d appreciate your help to get the last bit of things working.

This is what I have. See link https://www.cnet.com/products/acer-swift-3-sf315-52-52yn-15-6-core-i5-8250u-8-gb-ram-1-tb-hdd-us-international/

![Screen Shot 2020-12-04 at 10 47 29 AM](https://user-images.githubusercontent.com/75439065/101184344-9dd78c80-361e-11eb-98d5-6bebf5e3cc24.png)

**Comment by Quzard** [comment]
maybe this will help you
https://github.com/FallenChromium/Acer-Swift3-2018-hackintosh/issues/3#issuecomment-685132642

**Comment by professortex** [comment]
> maybe this will help you
> [#3 (comment)](https://github.com/FallenChromium/Acer-Swift3-2018-hackintosh/issues/3#issuecomment-685132642)

Thank you, i will review and see if it helps. this so completely different from clover and tonymacx86.

**Comment by Quzard** [comment]
> > maybe this will help you
> > [#3 (comment)](https://github.com/FallenChromium/Acer-Swift3-2018-hackintosh/issues/3#issuecomment-685132642)
> 
> Thank you, i will review and see if it helps. this so completely different from clover and tonymacx86.

https://dortania.github.io/OpenCore-Install-Guide/
This is the guide of opencore. Something maybe help.

**Comment by professortex** [comment]
> > > maybe this will help you
> > > [#3 (comment)](https://github.com/FallenChromium/Acer-Swift3-2018-hackintosh/issues/3#issuecomment-685132642)
> > 
> > 
> > Thank you, i will review and see if it helps. this so completely different from clover and tonymacx86.
> 
> https://dortania.github.io/OpenCore-Install-Guide/
> This is the guide of opencore. Something maybe help.

Thank you, but this is all greek to me. ive got no clue.

**Comment by professortex** [comment]
Learned!!
